# Generated by Django 5.1.1 on 2024-09-13 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_lectures'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
