# Generated by Django 5.1.1 on 2024-09-13 17:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_lectures_added_by_notes_added_by_notes_pdf'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('date', models.DateField(auto_now=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('img', models.FileField(blank=True, null=True, upload_to='routine_img/')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='routine_added', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
