# Generated by Django 5.1.1 on 2024-09-13 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_routine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='routine_images/'),
        ),
    ]
