# Generated by Django 5.1.1 on 2024-09-14 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_teacher_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='added_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers_added', to=settings.AUTH_USER_MODEL),
        ),
    ]
