# Generated by Django 5.1.1 on 2024-09-14 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_student_admission_date_student_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='roll_no',
            new_name='roll',
        ),
    ]
