# Generated by Django 5.1.1 on 2024-09-22 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_monthlysalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
