# Generated by Django 5.1.1 on 2024-09-22 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_period'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Routine',
        ),
    ]
