# Generated by Django 5.1.1 on 2024-09-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_alter_subject_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routine',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.subject'),
        ),
    ]
